import type { Metadata } from "next";
import { Baloo_Bhaijaan_2 } from 'next/font/google';
import localFont from 'next/font/local';
import "./globals.css";

const balooBhaijaan = Baloo_Bhaijaan_2({
  subsets: ['latin'],
  weight: ['400', '700'],
  variable: '--font-baloo', 
});

// 2. Configure Viner Hand ITC locally
const vinerHand = localFont({
  src: './fonts/VINERITC.ttf', 
  variable: '--font-viner',
});
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${balooBhaijaan.variable} ${vinerHand.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        {children}</body>
    </html>
  );
}
